version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: askdentist-nginx
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - askdentist-network

  php-fpm:
    build:
      context: ./infra/php
      dockerfile: Dockerfile
    container_name: askdentist-php
    volumes:
      - ./backend:/var/www/html
      - vendor-cache:/var/www/html/vendor
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=askdentist
      - DB_USERNAME=askdentist
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PUSHER_HOST=soketi
      - PUSHER_PORT=6001
    depends_on:
      - postgres
      - redis
    networks:
      - askdentist-network

  postgres:
    image: postgres:17-alpine
    container_name: askdentist-postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: askdentist
      POSTGRES_USER: askdentist
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - askdentist-network

  redis:
    image: redis:7-alpine
    container_name: askdentist-redis
    ports:
      - "16379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - askdentist-network

  soketi:
    image: quay.io/soketi/soketi:1.6-16-alpine
    container_name: askdentist-soketi
    ports:
      - "6001:6001"
    environment:
      SOKETI_DEBUG: "1"
      SOKETI_METRICS_SERVER_PORT: "9601"
      SOKETI_DEFAULT_APP_ID: "askdentist"
      SOKETI_DEFAULT_APP_KEY: "askdentist-key"
      SOKETI_DEFAULT_APP_SECRET: "askdentist-secret"
    networks:
      - askdentist-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: askdentist-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - askdentist-network

volumes:
  pgdata:
    driver: local
  redis-data:
    driver: local
  vendor-cache:
    driver: local

networks:
  askdentist-network:
    driver: bridge
