version: "3.9"
services:
  app:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ../backend:/var/www/html
      - ../backend/storage:/var/www/html/storage
    depends_on:
      - postgres
      - redis
    networks:
      - ask-dentist
    environment:
      - PHP_IDE_CONFIG=serverName=docker

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ask-dentist

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: askdentist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sql%40M88E22K
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ask-dentist

  redis:
    image: redis:7
    ports: ["6379:6379"]
    networks:
      - ask-dentist

  soketi:
    image: quay.io/soketi/soketi:1.6-16-alpine
    environment:
      SOKETI_DEBUG: "1"
      SOKETI_DEFAULT_APP_ID: "ask"
      SOKETI_DEFAULT_APP_KEY: "askkey"
      SOKETI_DEFAULT_APP_SECRET: "asksecret"
      SOKETI_METRICS_SERVER_PORT: "9601"
    ports: ["6001:6001","9601:9601"]
    networks:
      - ask-dentist

  mailhog:
    image: mailhog/mailhog
    ports: ["8025:8025","1025:1025"]
    networks:
      - ask-dentist

networks:
  ask-dentist:
    driver: bridge

volumes:
  postgres_data:
