name: ask_dentist_patient
description: Ask.Dentist patient mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.6.2

  # Network
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.0.5

  # Storage
  flutter_secure_storage: ^9.2.2

  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Internationalization
  intl: ^0.19.0

  # UI
  cupertino_icons: ^1.0.6
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  mockito: ^5.4.4

  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.1
  riverpod_generator: ^2.6.1

  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/.env.json
